import { Coffee } from "./app/shared/models/Coffee";
import { Tag } from "./app/shared/models/Tag";

export const sample_foods: Coffee[] = [
  {
    id:'1',
    name: ' Sierra',
    price: 10,
    favorite: false,
    origins: ['Bolivia'],
    stars: 4.5,
    imageUrl: 'assets/coffee-7.jpg',
    tags: ['Coffee'],
  },
  {
    id:'2',
    name: 'White Heron',
    price: 20,
    favorite: true,
    origins: ["Kenya"],
    stars: 4.7,
    imageUrl: 'assets/coffee-8.webp',
    tags: ['Coffee'],
  },
  {
    id:'3',
    name: 'Whole Beans',
    price: 5,
    favorite: false,
    origins: ['Uganda'],
    stars: 3.5,
    imageUrl: 'assets/coffee-3.jpg',
    tags: ['Coffee'],
  },
  {
    id:'4',
    name: 'Alamy',
    price: 2,
    favorite: true,
    origins: ['Ethiopia'],
    stars: 3.3,
    imageUrl: 'assets/coffee-4.jpg',
    tags: ['Coffee'],
  },
  {
    id:'5',
    name: 'Coffee Connection',
    price: 11,
    favorite: false,
    origins: ["Ethiopia"],
    stars: 3.0,
    imageUrl: 'assets/coffee-5.jpg',
    tags: ['Coffee'],

  },
  {
    id:'6',
    name: 'Boutique Cafe',
    price: 9,
    favorite: false,
    origins: ['Bolivia'],
    stars: 4.0,
    imageUrl: 'assets/coffee-6.jpg',
    tags: ['Coffee'],
  },
  {
    id:'7',
    name: 'Cinnamon',
    price: 9,
    favorite: false,
    origins: ['Bolivia'],
    stars: 4.0,
    imageUrl: 'assets/cinnamon.jpg',
    tags: ['Spice'],
  },
  {
    id:'8',
    name: 'Cumin',
    price: 9,
    favorite: false,
    origins: ['Ethiopia'],
    stars: 4.0,
    imageUrl: 'assets/cumin.jpg',
    tags: ['Spice'],
  },
  {
    id:'9',
    name: 'Ginger',
    price: 9,
    favorite: false,
    origins: ['Ethiopia'],
    stars: 4.0,
    imageUrl: 'assets/ginger.jpg',
    tags: ['Spice'],
  },
  {
    id:'10',
    name: 'Garlic',
    price: 9,
    favorite: false,
    origins: ['Bolivia'],
    stars: 4.0,
    imageUrl: 'assets/garlic.jpg',
    tags: ['Spice'],
  },
  {
    id:'11',
    name: 'Nutmeg',
    price: 9,
    favorite: false,
    origins: ['Ethiopia'],
    stars: 4.0,
    imageUrl: 'assets/nutmeg.jpg',
    tags: ['Spice'],
  },

]

export const sample_tags:Tag[] = [
  { name: 'All', count: 11 },
  { name: 'Coffee', count: 6 },
  { name: 'Spice', count: 5 },
]
